# Generated by Django 3.2.8 on 2021-10-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('link_on_photo', models.CharField(default='', max_length=200)),
                ('created_date', models.DateField()),
                ('sold_bouquets_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
