# Generated by Django 3.2.8 on 2021-10-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_qraphql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('link_on_photo', models.CharField(default='', max_length=200)),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bouquets', to='shop_qraphql.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('mail', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('service_income', models.IntegerField(default=0)),
                ('bouquet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase', to='shop_qraphql.bouquet')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='shop_qraphql.customer')),
            ],
        ),
    ]
